export const EXPERIENCE = {
  productionDurationSeconds: 245,
  fastModeMultiplier: 8,
  gaze: {
    dwellSeconds: 1.15,
    sceneThreeDwellSeconds: 0.7,
    transitionSafetySeconds: 7,
    startSafetySeconds: 0,
  },
  assets: {
    background: "./assets/img/tlo.png",
    images: {
      concert: "./assets/img/koncert.png",
      riots: "./assets/img/zamieszki.png",
      shadow: "./assets/img/cien.png",
      reflection: "./assets/img/odbicie.png",
      source: "./assets/img/idealna-falszywka.png",
    },
  },
  audio: {
    basePath: "./assets/audio/",
    background: null,
    backgroundVolume: 0.18,
    narrationVolume: 1,
    extensionFallbacks: ["mp3", "m4a", "wav"],
  },
  scenes: [
    {
      id: "scene-1-frame",
      imageKey: "concert",
      introImageKey: "riots",
      introAspect: 1.25,
      introWidth: 3.5,
      angleDeg: 0,
      aspect: 4.031,
      width: 6.6,
      duration: 45,
      nextPromptAt: 42,
      cues: [
        { id: "r1_01", duration: 12, pauseAfter: 0.6 },
        { id: "r1_02", duration: 14, pauseAfter: 0.6 },
        { id: "r1_03", duration: 13, pauseAfter: 0.6 },
      ],
      events: [
        { at: 3, action: "concertCropStart" },
        { at: 21, action: "concertReveal" },
      ],
    },
    {
      id: "scene-2-shadow",
      imageKey: "shadow",
      angleDeg: 34,
      aspect: 1.792,
      width: 4.95,
      duration: 55,
      nextPromptAt: 51,
      cues: [
        { id: "r2_01", duration: 11, pauseAfter: 0.45 },
        { id: "r2_02", duration: 10, pauseAfter: 0.45 },
        { id: "r2_03", duration: 12, pauseAfter: 0.45 },
        { id: "r2_04", duration: 12, pauseAfter: 0.45 },
      ],
      events: [
        { at: 8, action: "shadowSun" },
        { at: 18, action: "shadowPerson" },
        { at: 30, action: "shadowTower" },
        { at: 41, action: "shadowMissing" },
      ],
    },
    {
      id: "scene-3-reflection",
      imageKey: "reflection",
      angleDeg: 146,
      aspect: 1.792,
      width: 4.95,
      duration: 55,
      nextPromptAt: 51,
      cues: [
        { id: "r3_01", duration: 10, pauseAfter: 0.5 },
        { id: "r3_02", duration: 12, pauseAfter: 0.5 },
        { id: "r3_03", duration: 15, pauseAfter: 0.5 },
        { id: "r3_04", duration: 10, pauseAfter: 0.5 },
      ],
      events: [
        { at: 8, action: "enableReflectionSearch" },
        { at: 21, action: "reflectionSafetyReveal" },
      ],
    },
    {
      id: "scene-4-source",
      imageKey: "source",
      angleDeg: 102,
      aspect: 1.792,
      width: 4.95,
      duration: 55,
      nextPromptAt: 51,
      cues: [
        { id: "r4_01", duration: 12, pauseAfter: 0.5 },
        { id: "r4_02", duration: 12, pauseAfter: 0.5 },
        { id: "r4_03", duration: 15, pauseAfter: 0.5 },
        { id: "r4_04", duration: 10, pauseAfter: 0.5 },
      ],
      events: [
        { at: 8, action: "sourceSearch" },
        { at: 28, action: "sourceNoTrace" },
        { at: 36, action: "sourceTriptych" },
      ],
    },
  ],
  closing: {
    duration: 30,
    cues: [
      { id: "r5_01", duration: 9, pauseAfter: 0.7 },
      { id: "r5_02", duration: 9, pauseAfter: 0.7 },
      { id: "r5_03", duration: 9, pauseAfter: 0.7 },
    ],
  },
};
